### ISSUE TITLE
Don't call load on a PDF View without recycling it first

### ISSUE THREAD

**Issue by Finneah** [rumax/react-native-PDFView#184]
I have saved several PDF files. If after one PDF is displayed another one is displayed this error occurse. 
Does anyone have an idea how I can fix this?
In the screen `Archive`
```
2021-02-02 12:24:33.297 27266-27266/com.afriso.toolbox E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.afriso.toolbox, PID: 27266
    java.lang.IllegalStateException: Don't call load on a PDF View without recycling it first.
        at com.github.barteksc.pdfviewer.PDFView.load(PDFView.java:353)
        at com.github.barteksc.pdfviewer.PDFView.load(PDFView.java:347)
        at com.github.barteksc.pdfviewer.PDFView.access$2000(PDFView.java:83)
        at com.github.barteksc.pdfviewer.PDFView$Configurator$1.run(PDFView.java:1585)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

```
My Screen
```
 <PDFPreview
   visible={this.state.showModalPreview}
   pdf={this.state.item}
   onClose={this._closePreview.bind(this)}
   />
          <SectionList
              // ... more Code
              sections={sections ? sections : []}
              renderItem={({item}) => (
              <ListItem
              onPress={() => {
                  this.setState({
                  item: item,
                  showModalPreview: true
                  });
              }}>
            //  ... more Code
              </ListItem>
            )}
            />
```

**Comment by rumax** [comment]
Hi @Finneah, that issue comes from the https://github.com/barteksc/AndroidPdfViewer/issues/464, therefore, try to use release 3.0.0-beta.5.

**Comment by Finneah** [comment]
> Hi @Finneah, that issue comes from the [barteksc/AndroidPdfViewer#464](https://github.com/barteksc/AndroidPdfViewer/issues/464), therefore, try to use release 3.0.0-beta.5.

Thanks for your fast help. I will test it asap.

**Comment by Finneah** [comment]
i tried `release 3.0.0-beta.5` and `3.1.0-beta.1` but it still happens. I think i have to wait till pdfViewer will be updated again. But thanks for your help
